stages:
  - kirkstone
  - scarthgap
  - test

variables:
  TEST_BIN_DIR: test_binaries

### BUILDING ###
.build-base:
  image: ghcr.io/siemens/kas/kas:4.0
  tags:
    - yocto
  needs: []
  variables:
    IMAGE_DIR: build/tmp/deploy/images/${CI_BITBAKE_MACHINE}
  before_script:
    - find dependencies -name "*tar.gz" -exec tar xf '{}' \; || true
    - rm -rf downloads/git2
    - mkdir -p ${TEST_BIN_DIR}
  script:
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:${CI_KAS_LINUX}:${CI_KAS_UBOOT}:${CI_KAS_TFA}
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - cp -L ${IMAGE_DIR}/${KERNEL} ${TEST_BIN_DIR}
    - cp -L ${IMAGE_DIR}/${ROOTFS} ${TEST_BIN_DIR}
    - cp -L ${IMAGE_DIR}/${DTB} ${TEST_BIN_DIR}
  after_script:
    - mkdir -p dependencies
    - |
      for repo in meta-arm meta-linux-mainline poky; do
        if [ -d "${repo}" ]; then
          tar czf dependencies/"${repo}".tar.gz "${repo}"
        fi
      done
    - rm -rf downloads/git2
    - echo "BUILD_JOB_ID=${CI_JOB_ID}" > job.env
    - echo "BITBAKE_MACHINE=${CI_BITBAKE_MACHINE}" >> job.env
  cache:
    - key: "downloads"
      paths:
        - downloads
    - key: "sstate-cache"
      paths:
        - sstate-cache
    - key: "dependencies"
      paths:
        - dependencies
  retry: 2
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 2 weeks
    reports:
      dotenv: job.env
    paths:
      - build/conf/
      - build/tmp/deploy/images/
      - build/tmp/deploy/licenses/
      - build/tmp/work*/**/temp/log.do_*.*
      - ${TEST_BIN_DIR}

.build-mainline:
  extends: .build-base
  variables:
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_LINUX: kas/kernel/mainline.yml
    CI_KAS_UBOOT: kas/u-boot/mainline-2023.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/mainline-2.9.0.yml

.build-cip-5.10:
  extends: .build-base
  variables:
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_UBOOT: kas/u-boot/mainline-2023.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/mainline-2.9.0.yml
    CI_KAS_LINUX: kas/kernel/cip-5.10.yml

.build-cip-6.1:
  extends: .build-base
  variables:
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_UBOOT: kas/u-boot/mainline-2023.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/mainline-2.9.0.yml
    CI_KAS_LINUX: kas/kernel/cip-6.1.yml

.build-bsp:
  extends: .build-base
  variables:
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_LINUX: kas/kernel/renesas-5.10.yml
    CI_KAS_UBOOT: kas/u-boot/renesas-2021.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/renesas-2.9.0.yml

.kirkstone:
  stage: kirkstone
  variables:
    CI_KAS_YOCTO: kas/yocto/kirkstone.yml

.scarthgap:
  stage: scarthgap
  variables:
    CI_KAS_YOCTO: kas/yocto/scarthgap.yml

.hihope-rzg2h:
  variables:
    CI_BITBAKE_MACHINE: hihope-rzg2h
    CI_KAS_MACHINE: kas/machine/hihope-rzg2h.yml

.rzg2l-family:
  variables:
    # Mainline bootloaders do not support this platform yet
    CI_KAS_UBOOT: kas/u-boot/renesas-2021.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/renesas-2.9.0.yml

.smarc-rzg2l:
  extends: [.rzg2l-family]
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2l
    CI_KAS_MACHINE: kas/machine/smarc-rzg2l.yml

.smarc-rzg2lc:
  extends: [.rzg2l-family]
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2lc
    CI_KAS_MACHINE: kas/machine/smarc-rzg2lc.yml

.smarc-rzg2ul:
  extends: [.rzg2l-family]
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2ul
    CI_KAS_MACHINE: kas/machine/smarc-rzg2ul.yml

# Build jobs
build:kirkstone:hihope-rzg2h-mainline:
  extends: [.build-mainline, .kirkstone, .hihope-rzg2h]

build:kirkstone:hihope-rzg2h-cip-5.10:
  extends: [.build-cip-5.10, .kirkstone, .hihope-rzg2h]

build:kirkstone:hihope-rzg2h-cip-6.1:
  extends: [.build-cip-5.10, .kirkstone, .hihope-rzg2h]

build:kirkstone:hihope-rzg2h-bsp:
  extends: [.build-bsp, .kirkstone, .hihope-rzg2h]

build:kirkstone:smarc-rzg2l-mainline:
  extends: [.build-mainline, .kirkstone, .smarc-rzg2l]

build:kirkstone:smarc-rzg2l-cip-5.10:
  extends: [.build-cip-5.10, .kirkstone, .smarc-rzg2l]

build:kirkstone:smarc-rzg2l-cip-6.1:
  extends: [.build-cip-6.1, .kirkstone, .smarc-rzg2l]

build:kirkstone:smarc-rzg2l-bsp:
  extends: [.build-bsp, .kirkstone, .smarc-rzg2l]

build:kirkstone:smarc-rzg2lc-mainline:
  extends: [.build-mainline, .kirkstone, .smarc-rzg2lc]

build:kirkstone:smarc-rzg2lc-cip-5.10:
  extends: [.build-cip-5.10, .kirkstone, .smarc-rzg2lc]

build:kirkstone:smarc-rzg2lc-cip-6.1:
  extends: [.build-cip-6.1, .kirkstone, .smarc-rzg2lc]

build:kirkstone:smarc-rzg2lc-bsp:
  extends: [.build-bsp, .kirkstone, .smarc-rzg2lc]

build:kirkstone:smarc-rzg2ul-mainline:
  extends: [.build-mainline, .kirkstone, .smarc-rzg2ul]

build:kirkstone:smarc-rzg2ul-cip-5.10:
  extends: [.build-cip-5.10, .kirkstone, .smarc-rzg2ul]

build:kirkstone:smarc-rzg2ul-cip-6.1:
  extends: [.build-cip-6.1, .kirkstone, .smarc-rzg2ul]

build:kirkstone:smarc-rzg2ul-bsp:
  extends: [.build-bsp, .kirkstone, .smarc-rzg2ul]

build:scarthgap:hihope-rzg2h-mainline:
  extends: [.build-mainline, .scarthgap, .hihope-rzg2h]

build:scarthgap:hihope-rzg2h-cip-5.10:
  extends: [.build-cip-5.10, .scarthgap, .hihope-rzg2h]

build:scarthgap:hihope-rzg2h-cip-6.1:
  extends: [.build-cip-5.10, .scarthgap, .hihope-rzg2h]

build:scarthgap:hihope-rzg2h-bsp:
  extends: [.build-bsp, .scarthgap, .hihope-rzg2h]

build:scarthgap:smarc-rzg2l-mainline:
  extends: [.build-mainline, .scarthgap, .smarc-rzg2l]

build:scarthgap:smarc-rzg2l-cip-5.10:
  extends: [.build-cip-5.10, .scarthgap, .smarc-rzg2l]

build:scarthgap:smarc-rzg2l-cip-6.1:
  extends: [.build-cip-6.1, .scarthgap, .smarc-rzg2l]

build:scarthgap:smarc-rzg2l-bsp:
  extends: [.build-bsp, .scarthgap, .smarc-rzg2l]

build:scarthgap:smarc-rzg2lc-mainline:
  extends: [.build-mainline, .scarthgap, .smarc-rzg2lc]

build:scarthgap:smarc-rzg2lc-cip-5.10:
  extends: [.build-cip-5.10, .scarthgap, .smarc-rzg2lc]

build:scarthgap:smarc-rzg2lc-cip-6.1:
  extends: [.build-cip-6.1, .scarthgap, .smarc-rzg2lc]

build:scarthgap:smarc-rzg2lc-bsp:
  extends: [.build-bsp, .scarthgap, .smarc-rzg2lc]

build:scarthgap:smarc-rzg2ul-mainline:
  extends: [.build-mainline, .scarthgap, .smarc-rzg2ul]

build:scarthgap:smarc-rzg2ul-cip-5.10:
  extends: [.build-cip-5.10, .scarthgap, .smarc-rzg2ul]

build:scarthgap:smarc-rzg2ul-cip-6.1:
  extends: [.build-cip-6.1, .scarthgap, .smarc-rzg2ul]

build:scarthgap:smarc-rzg2ul-bsp:
  extends: [.build-bsp, .scarthgap, .smarc-rzg2ul]

### TESTING ###
# BUILD_JOB_ID AND BITBAKE_MACHINE come from job.env shared from the build job
.test-base:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  stage: test
  tags:
    - lava-job
  script:
    - mkdir -p results
    - export
    - scripts/submit-lava-job.sh -d -u spl2-bot -b scripts/lava-templates/base-template.yaml -e scripts/lava-env/${BITBAKE_MACHINE}.env -j results -g ${BUILD_JOB_ID} -f ${TEST_BIN_DIR} ${TESTS}
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 1 year
    reports:
      junit: results/results*.xml
    paths:
      - results

.test-cases:
  variables:
    TESTS: "-t scripts/lava-templates/test-uname.yaml"

# Test jobs
test:kirkstone:hihope-rzg2h-mainline:
  needs: ["build:kirkstone:hihope-rzg2h-mainline"]
  extends: [.test-base, .test-cases]

test:kirkstone:hihope-rzg2h-cip-5.10:
  needs: ["build:kirkstone:hihope-rzg2h-cip-5.10"]
  extends: [.test-base, .test-cases]

test:kirkstone:hihope-rzg2h-cip-6.1:
  needs: ["build:kirkstone:hihope-rzg2h-cip-6.1"]
  extends: [.test-base, .test-cases]

test:kirkstone:hihope-rzg2h-bsp:
  needs: ["build:kirkstone:hihope-rzg2h-bsp"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2l-mainline:
  needs: ["build:kirkstone:smarc-rzg2l-mainline"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2l-cip-5.10:
  needs: ["build:kirkstone:smarc-rzg2l-cip-5.10"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2l-cip-6.1:
  needs: ["build:kirkstone:smarc-rzg2l-cip-6.1"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2l-bsp:
  needs: ["build:kirkstone:smarc-rzg2l-bsp"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2lc-mainline:
  needs: ["build:kirkstone:smarc-rzg2lc-mainline"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2lc-cip-5.10:
  needs: ["build:kirkstone:smarc-rzg2lc-cip-5.10"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2lc-cip-6.1:
  needs: ["build:kirkstone:smarc-rzg2lc-cip-6.1"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2lc-bsp:
  needs: ["build:kirkstone:smarc-rzg2lc-bsp"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2ul-mainline:
  needs: ["build:kirkstone:smarc-rzg2ul-mainline"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2ul-cip-5.10:
  needs: ["build:kirkstone:smarc-rzg2ul-cip-5.10"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2ul-cip-6.1:
  needs: ["build:kirkstone:smarc-rzg2ul-cip-6.1"]
  extends: [.test-base, .test-cases]

test:kirkstone:smarc-rzg2ul-bsp:
  needs: ["build:kirkstone:smarc-rzg2ul-bsp"]
  extends: [.test-base, .test-cases]

test:scarthgap:hihope-rzg2h-mainline:
  needs: ["build:scarthgap:hihope-rzg2h-mainline"]
  extends: [.test-base, .test-cases]

test:scarthgap:hihope-rzg2h-cip-5.10:
  needs: ["build:scarthgap:hihope-rzg2h-cip-5.10"]
  extends: [.test-base, .test-cases]

test:scarthgap:hihope-rzg2h-cip-6.1:
  needs: ["build:scarthgap:hihope-rzg2h-cip-6.1"]
  extends: [.test-base, .test-cases]

test:scarthgap:hihope-rzg2h-bsp:
  needs: ["build:scarthgap:hihope-rzg2h-bsp"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2l-mainline:
  needs: ["build:scarthgap:smarc-rzg2l-mainline"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2l-cip-5.10:
  needs: ["build:scarthgap:smarc-rzg2l-cip-5.10"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2l-cip-6.1:
  needs: ["build:scarthgap:smarc-rzg2l-cip-6.1"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2l-bsp:
  needs: ["build:scarthgap:smarc-rzg2l-bsp"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2lc-mainline:
  needs: ["build:scarthgap:smarc-rzg2lc-mainline"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2lc-cip-5.10:
  needs: ["build:scarthgap:smarc-rzg2lc-cip-5.10"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2lc-cip-6.1:
  needs: ["build:scarthgap:smarc-rzg2lc-cip-6.1"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2lc-bsp:
  needs: ["build:scarthgap:smarc-rzg2lc-bsp"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2ul-mainline:
  needs: ["build:scarthgap:smarc-rzg2ul-mainline"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2ul-cip-5.10:
  needs: ["build:scarthgap:smarc-rzg2ul-cip-5.10"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2ul-cip-6.1:
  needs: ["build:scarthgap:smarc-rzg2ul-cip-6.1"]
  extends: [.test-base, .test-cases]

test:scarthgap:smarc-rzg2ul-bsp:
  needs: ["build:scarthgap:smarc-rzg2ul-bsp"]
  extends: [.test-base, .test-cases]
