image: ghcr.io/siemens/kas/kas:4.0

stages:
  - build

.build-base:
  stage: build
  tags:
    - yocto
  needs: []
  script:
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:${CI_KAS_LINUX}:${CI_KAS_UBOOT}:${CI_KAS_TFA}
  cache:
    - key: "downloads"
      paths:
        - downloads
    - key: "sstate-cache"
      paths:
        - sstate-cache
    - key: "dependencies"
      paths:
        - poky
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 2 weeks
    paths:
      - build/conf/
      - build/tmp/deploy/images/
      - build/tmp/deploy/licenses/

.build-cip:
  extends: .build-base
  variables:
    CI_KAS_YOCTO: kas/yocto/kirkstone.yml
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_UBOOT: kas/u-boot/mainline-2023.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/mainline-2.9.0.yml
  parallel:
    matrix:
      - CI_KAS_LINUX:
        - kas/kernel/cip-5.10.yml
        - kas/kernel/cip-6.1.yml

.build-bsp:
  extends: .build-base
  variables:
    CI_KAS_YOCTO: kas/yocto/kirkstone.yml
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml
    CI_KAS_LINUX: kas/kernel/renesas-5.10.yml
    CI_KAS_UBOOT: kas/u-boot/renesas-2021.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/renesas-2.9.0.yml

.hihope-rzg2h:
  variables:
    CI_KAS_MACHINE: kas/machine/hihope-rzg2h.yml

.smarc-rzg2l:
  variables:
    CI_KAS_MACHINE: kas/machine/smarc-rzg2l.yml
    # Mainline bootloaders do not support this platform yet
    CI_KAS_UBOOT: kas/u-boot/renesas-2021.10.yml
    CI_KAS_TFA: kas/trusted-firmware-a/renesas-2.9.0.yml

hihope-rzg2h-cip:
  extends: [.build-cip, .hihope-rzg2h]

hihope-rzg2h-bsp:
  extends: [.build-bsp, .hihope-rzg2h]

smarc-rzg2l-cip:
  extends: [.build-cip, .smarc-rzg2l]

smarc-rzg2l-bsp:
  extends: [.build-bsp, .smarc-rzg2l]
