stages:
  - clear-caches
  - build:kirkstone
  - build:scarthgap
  - test:kirkstone
  - test:scarthgap

variables:
  TEST_BIN_DIR: test_binaries
  BUILD_OUTPUT_DIR: build_output

### CLEAR CACHES ###
clear-sstate:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  stage: clear-caches
  cache:
    - key: "sstate-cache"
      paths:
        - sstate-cache
  script:
    - sudo rm -rf sstate-cache/*
  rules:
    - if: $CLEAR_SSTATE_CACHE == "true"

clear-downloads:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  stage: clear-caches
  cache:
    - key: "downloads"
      paths:
        - downloads
  script:
    - sudo rm -rf downloads/*
  rules:
    - if: $CLEAR_DOWNLOADS_CACHE == "true"

clear-dependencies:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  stage: clear-caches
  cache:
    - key: "dependencies"
      paths:
        - dependencies
  script:
    - sudo rm -rf dependencies/*
  rules:
    - if: $CLEAR_DEPENDENCIES_CACHE == "true"

### BUILDING ###
.build-base:
  image: ghcr.io/siemens/kas/kas:4.0
  tags:
    - yocto
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CLEAR_SSTATE_CACHE == "true"
      needs: [clear-sstate]
    - if: $CLEAR_DOWNLOADS_CACHE == "true"
      needs: [clear-downloads]
    - if: $CLEAR_DEPENDENCIES_CACHE == "true"
      needs: [clear-dependencies]
    - if: $CLEAR_SSTATE_CACHE != "true"
    - if: $CLEAR_DOWNLOADS_CACHE != "true"
    - if: $CLEAR_DEPENDENCIES_CACHE != "true"
  before_script:
    - find dependencies -name "*tar.gz" -exec tar xf '{}' \; || true
    - rm -rf downloads/git2
  after_script:
    - mkdir -p dependencies
    - |
      for repo in meta-arm meta-linux-mainline poky; do
        if [ -d "${repo}" ]; then
          tar czf dependencies/"${repo}".tar.gz "${repo}"
        fi
      done
    - rm -rf downloads/git2
    - echo "BUILD_JOB_ID=${CI_JOB_ID}" > job.env
    - echo "BITBAKE_MACHINE=${CI_BITBAKE_MACHINE}" >> job.env
  cache:
    - key: "downloads"
      paths:
        - downloads
    - key: "sstate-cache"
      paths:
        - sstate-cache
    - key: "dependencies"
      paths:
        - dependencies
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 2 weeks
    reports:
      dotenv: job.env
    paths:
      - ${TEST_BIN_DIR}
      - ${BUILD_OUTPUT_DIR}
      - build/tmp/work*/**/temp/log.do_*.*

.build-g2h-family-mainline: &build-g2h-family-mainline
    # kernel: mainline
    # u-boot: mainline-2023.10
    # tf-a: mainline-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/mainline.yml:kas/u-boot/mainline-2023.10.yml:kas/trusted-firmware-a/mainline-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/mainline ${BUILD_OUTPUT_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/mainline
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/mainline
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/mainline
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/mainline

.build-g2h-family-cip-510: &build-g2h-family-cip-510
    # kernel: cip-5.10
    # u-boot: mainline-2023.10
    # tf-a: mainline-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-5.10.yml:kas/u-boot/mainline-2023.10.yml:kas/trusted-firmware-a/mainline-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/cip-5.10 ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/cip-5.10
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/cip-5.10

.build-g2h-family-cip-61: &build-g2h-family-cip-61
    # kernel: cip-6.1
    # u-boot: mainline-2023.10
    # tf-a: mainline-2.9.0
    - kas build kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.1.yml:kas/u-boot/mainline-2023.10.yml:kas/trusted-firmware-a/mainline-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/cip-6.1 ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/cip-6.1
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/cip-6.1

.build-g2h-family-bsp: &build-g2h-family-bsp
    # kernel: renesas-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/renesas-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/renesas-5.10 ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/renesas-5.10
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/renesas-5.10

.build-g2l-family-mainline: &build-g2l-family-mainline
    # Mainline bootloaders do not support this family yet
    # kernel: mainline
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/mainline.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/mainline ${BUILD_OUTPUT_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/mainline
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/mainline
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/mainline
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/mainline
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/mainline

.build-g2l-family-cip-510: &build-g2l-family-cip-510
    # kernel: cip-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/cip-5.10 ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/cip-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/cip-5.10
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/cip-5.10
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/cip-5.10

.build-g2l-family-cip-61: &build-g2l-family-cip-61
    # kernel: cip-6.1
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/cip-6.1.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/cip-6.1 ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/cip-6.1
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/cip-6.1
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/cip-6.1
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/cip-6.1

.build-g2l-family-bsp: &build-g2l-family-bsp
    # kernel: renesas-5.10
    # u-boot: renesas-2021.10
    # tf-a: renesas-2.9.0
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE}:kas/kernel/renesas-5.10.yml:kas/u-boot/renesas-2021.10.yml:kas/trusted-firmware-a/renesas-2.9.0.yml
    - source scripts/lava-env/${CI_BITBAKE_MACHINE}.env
    - mkdir -p ${TEST_BIN_DIR}/renesas-5.10 ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${KERNEL} ${TEST_BIN_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${ROOTFS} ${TEST_BIN_DIR}/renesas-5.10
    - cp -L build/tmp/deploy/images/${CI_BITBAKE_MACHINE}/${DTB} ${TEST_BIN_DIR}/renesas-5.10
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -r build/tmp/deploy/images ${BUILD_OUTPUT_DIR}/renesas-5.10
    - cp -r build/tmp/deploy/licenses ${BUILD_OUTPUT_DIR}/renesas-5.10

.build-sdk:
  when: manual
  script:
    # kernel: default
    # u-boot: default
    # tf-a: default
    - kas build --update --force-checkout kas/opt/gitlab-ci-cache.yml:kas/opt/debug.yml:${CI_KAS_YOCTO}:${CI_KAS_IMAGE}:${CI_KAS_MACHINE} --cmd populate_sdk
    - mkdir -p ${BUILD_OUTPUT_DIR}/sdk
    - cp -r build/conf ${BUILD_OUTPUT_DIR}/sdk
    - cp -r build/tmp/deploy/sdk ${BUILD_OUTPUT_DIR}/sdk

.renesas-image-minimal:
  extends: .build-base
  variables:
    CI_KAS_IMAGE: kas/image/renesas-image-minimal.yml

.build-kirkstone:
  stage: build:kirkstone
  variables:
    CI_KAS_YOCTO: kas/yocto/kirkstone.yml

.build-scarthgap:
  stage: build:scarthgap
  variables:
    CI_KAS_YOCTO: kas/yocto/scarthgap.yml

.kirkstone-g2h-family:
  extends: .build-kirkstone
  script:
    - *build-g2h-family-cip-510
    - *build-g2h-family-cip-61
    - *build-g2h-family-bsp

.kirkstone-g2l-family:
  extends: .build-kirkstone
  script:
    - *build-g2l-family-cip-510
    - *build-g2l-family-cip-61
    - *build-g2l-family-bsp

.scarthgap-g2h-family:
  extends: .build-scarthgap
  script:
    - *build-g2h-family-mainline
    - *build-g2h-family-cip-510
    - *build-g2h-family-cip-61
    - *build-g2h-family-bsp

.scarthgap-g2l-family:
  extends: .build-scarthgap
  script:
    - *build-g2l-family-mainline
    - *build-g2l-family-cip-510
    - *build-g2l-family-cip-61
    - *build-g2l-family-bsp

.hihope-rzg2h:
  variables:
    CI_BITBAKE_MACHINE: hihope-rzg2h
    CI_KAS_MACHINE: kas/machine/hihope-rzg2h.yml

.smarc-rzg2l:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2l
    CI_KAS_MACHINE: kas/machine/smarc-rzg2l.yml

.smarc-rzg2lc:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2lc
    CI_KAS_MACHINE: kas/machine/smarc-rzg2lc.yml

.smarc-rzg2ul:
  variables:
    CI_BITBAKE_MACHINE: smarc-rzg2ul
    CI_KAS_MACHINE: kas/machine/smarc-rzg2ul.yml

# Build jobs
build:kirkstone:hihope-rzg2h:
  extends: [.renesas-image-minimal, .kirkstone-g2h-family, .hihope-rzg2h]

build:kirkstone:smarc-rzg2l:
  extends: [.renesas-image-minimal, .kirkstone-g2l-family, .smarc-rzg2l]

build:kirkstone:smarc-rzg2lc:
  extends: [.renesas-image-minimal, .kirkstone-g2l-family, .smarc-rzg2lc]

build:kirkstone:smarc-rzg2ul:
  extends: [.renesas-image-minimal, .kirkstone-g2l-family, .smarc-rzg2ul]

build:scarthgap:hihope-rzg2h:
  extends: [.renesas-image-minimal, .scarthgap-g2h-family, .hihope-rzg2h]

build:scarthgap:smarc-rzg2l:
  extends: [.renesas-image-minimal, .scarthgap-g2l-family, .smarc-rzg2l]

build:scarthgap:smarc-rzg2lc:
  extends: [.renesas-image-minimal, .scarthgap-g2l-family, .smarc-rzg2lc]

build:scarthgap:smarc-rzg2ul:
  extends: [.renesas-image-minimal, .scarthgap-g2l-family, .smarc-rzg2ul]

# SDK build jobs
build:sdk:kirkstone:hihope-rzg2h:
  extends: [.renesas-image-minimal, .build-kirkstone, .hihope-rzg2h, .build-sdk]

build:sdk:kirkstone:smarc-rzg2l:
  extends: [.renesas-image-minimal, .build-kirkstone, .smarc-rzg2l, .build-sdk]

build:sdk:kirkstone:smarc-rzg2lc:
  extends: [.renesas-image-minimal, .build-kirkstone, .smarc-rzg2lc, .build-sdk]

build:sdk:kirkstone:smarc-rzg2ul:
  extends: [.renesas-image-minimal, .build-kirkstone, .smarc-rzg2ul, .build-sdk]

build:sdk:scarthgap:hihope-rzg2h:
  extends: [.renesas-image-minimal, .build-scarthgap, .hihope-rzg2h, .build-sdk]

build:sdk:scarthgap:smarc-rzg2l:
  extends: [.renesas-image-minimal, .build-scarthgap, .smarc-rzg2l, .build-sdk]

build:sdk:scarthgap:smarc-rzg2lc:
  extends: [.renesas-image-minimal, .build-scarthgap, .smarc-rzg2lc, .build-sdk]

build:sdk:scarthgap:smarc-rzg2ul:
  extends: [.renesas-image-minimal, .build-scarthgap, .smarc-rzg2ul, .build-sdk]

### TESTING ###
# BUILD_JOB_ID AND BITBAKE_MACHINE come from job.env shared from the build job
.test-base:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  tags:
    - lava-job
  script:
    - mkdir -p results
    - export
    - scripts/submit-lava-job.sh -d -u spl2-bot -b scripts/lava-templates/base-template.yaml -e scripts/lava-env/${BITBAKE_MACHINE}.env -j results -g ${BUILD_JOB_ID} -f ${BIN_DIR} ${TESTS}
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 1 year
    reports:
      junit: results/results*.xml
    paths:
      - results

.test-cases:
  variables:
    TESTS: "-t scripts/lava-templates/test-uname.yaml"

# Test jobs
test:kirkstone:hihope-rzg2h-cip-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:kirkstone:hihope-rzg2h-cip-6.1:
  stage: test:kirkstone
  needs: ["build:kirkstone:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:kirkstone:hihope-rzg2h-renesas-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:kirkstone:smarc-rzg2l-cip-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:kirkstone:smarc-rzg2l-cip-6.1:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:kirkstone:smarc-rzg2l-renesas-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:kirkstone:smarc-rzg2lc-cip-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:kirkstone:smarc-rzg2lc-cip-6.1:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:kirkstone:smarc-rzg2lc-renesas-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:kirkstone:smarc-rzg2ul-cip-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:kirkstone:smarc-rzg2ul-cip-6.1:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:kirkstone:smarc-rzg2ul-renesas-5.10:
  stage: test:kirkstone
  needs: ["build:kirkstone:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:scarthgap:hihope-rzg2h-mainline:
  stage: test:scarthgap
  needs: ["build:scarthgap:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/mainline

test:scarthgap:hihope-rzg2h-cip-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:scarthgap:hihope-rzg2h-cip-6.1:
  stage: test:scarthgap
  needs: ["build:scarthgap:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:scarthgap:hihope-rzg2h-renesas-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:hihope-rzg2h"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:scarthgap:smarc-rzg2l-mainline:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/mainline

test:scarthgap:smarc-rzg2l-cip-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:scarthgap:smarc-rzg2l-cip-6.1:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:scarthgap:smarc-rzg2l-renesas-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2l"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:scarthgap:smarc-rzg2lc-mainline:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/mainline

test:scarthgap:smarc-rzg2lc-cip-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:scarthgap:smarc-rzg2lc-cip-6.1:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:scarthgap:smarc-rzg2lc-renesas-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2lc"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10

test:scarthgap:smarc-rzg2ul-mainline:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/mainline

test:scarthgap:smarc-rzg2ul-cip-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-5.10

test:scarthgap:smarc-rzg2ul-cip-6.1:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/cip-6.1

test:scarthgap:smarc-rzg2ul-renesas-5.10:
  stage: test:scarthgap
  needs: ["build:scarthgap:smarc-rzg2ul"]
  extends: [.test-base, .test-cases]
  variables:
    BIN_DIR: ${TEST_BIN_DIR}/renesas-5.10
